# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x12\tbomberman\"?\n\x04Tile\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12!\n\x04type\x18\x03 \x01(\x0e\x32\x13.bomberman.TileType\"D\n\x03Map\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x1e\n\x05tiles\x18\x03 \x03(\x0b\x32\x0f.bomberman.Tile\"Q\n\x06Player\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05pos_x\x18\x02 \x01(\x05\x12\r\n\x05pos_y\x18\x03 \x01(\x05\x12\r\n\x05\x61live\x18\x04 \x01(\x08\x12\x0e\n\x06points\x18\x05 \x01(\x05\"a\n\tGameState\x12\x13\n\x0bnum_players\x18\x01 \x01(\x05\x12\"\n\x07players\x18\x02 \x03(\x0b\x32\x11.bomberman.Player\x12\x1b\n\x03map\x18\x03 \x01(\x0b\x32\x0e.bomberman.Map\"e\n\nPlayerMove\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12&\n\tmove_type\x18\x02 \x01(\x0e\x32\x13.bomberman.MoveType\x12\r\n\x05pos_x\x18\x03 \x01(\x05\x12\r\n\x05pos_y\x18\x04 \x01(\x05\">\n\x0cInitialState\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12\x1b\n\x03map\x18\x02 \x01(\x0b\x32\x0e.bomberman.Map*X\n\x08TileType\x12\t\n\x05\x45MPTY\x10\x00\x12\x12\n\x0e\x42REAKABLE_WALL\x10\x01\x12\x14\n\x10UNBREAKABLE_WALL\x10\x02\x12\x08\n\x04\x42OMB\x10\x03\x12\r\n\tEXPLOSION\x10\x04*=\n\x08MoveType\x12\x08\n\x04IDLE\x10\x00\x12\x0f\n\x0bPLACED_BOMB\x10\x01\x12\t\n\x05MOVED\x10\x02\x12\x0b\n\x07RESTART\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TILETYPE']._serialized_start=509
  _globals['_TILETYPE']._serialized_end=597
  _globals['_MOVETYPE']._serialized_start=599
  _globals['_MOVETYPE']._serialized_end=660
  _globals['_TILE']._serialized_start=25
  _globals['_TILE']._serialized_end=88
  _globals['_MAP']._serialized_start=90
  _globals['_MAP']._serialized_end=158
  _globals['_PLAYER']._serialized_start=160
  _globals['_PLAYER']._serialized_end=241
  _globals['_GAMESTATE']._serialized_start=243
  _globals['_GAMESTATE']._serialized_end=340
  _globals['_PLAYERMOVE']._serialized_start=342
  _globals['_PLAYERMOVE']._serialized_end=443
  _globals['_INITIALSTATE']._serialized_start=445
  _globals['_INITIALSTATE']._serialized_end=507
# @@protoc_insertion_point(module_scope)
