/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: game.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "game.pb-c.h"
void   bomberman__tile__init
                     (Bomberman__Tile         *message)
{
  static const Bomberman__Tile init_value = BOMBERMAN__TILE__INIT;
  *message = init_value;
}
size_t bomberman__tile__get_packed_size
                     (const Bomberman__Tile *message)
{
  assert(message->base.descriptor == &bomberman__tile__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bomberman__tile__pack
                     (const Bomberman__Tile *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bomberman__tile__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bomberman__tile__pack_to_buffer
                     (const Bomberman__Tile *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bomberman__tile__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Bomberman__Tile *
       bomberman__tile__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Bomberman__Tile *)
     protobuf_c_message_unpack (&bomberman__tile__descriptor,
                                allocator, len, data);
}
void   bomberman__tile__free_unpacked
                     (Bomberman__Tile *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bomberman__tile__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bomberman__map__init
                     (Bomberman__Map         *message)
{
  static const Bomberman__Map init_value = BOMBERMAN__MAP__INIT;
  *message = init_value;
}
size_t bomberman__map__get_packed_size
                     (const Bomberman__Map *message)
{
  assert(message->base.descriptor == &bomberman__map__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bomberman__map__pack
                     (const Bomberman__Map *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bomberman__map__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bomberman__map__pack_to_buffer
                     (const Bomberman__Map *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bomberman__map__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Bomberman__Map *
       bomberman__map__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Bomberman__Map *)
     protobuf_c_message_unpack (&bomberman__map__descriptor,
                                allocator, len, data);
}
void   bomberman__map__free_unpacked
                     (Bomberman__Map *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bomberman__map__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bomberman__player__init
                     (Bomberman__Player         *message)
{
  static const Bomberman__Player init_value = BOMBERMAN__PLAYER__INIT;
  *message = init_value;
}
size_t bomberman__player__get_packed_size
                     (const Bomberman__Player *message)
{
  assert(message->base.descriptor == &bomberman__player__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bomberman__player__pack
                     (const Bomberman__Player *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bomberman__player__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bomberman__player__pack_to_buffer
                     (const Bomberman__Player *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bomberman__player__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Bomberman__Player *
       bomberman__player__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Bomberman__Player *)
     protobuf_c_message_unpack (&bomberman__player__descriptor,
                                allocator, len, data);
}
void   bomberman__player__free_unpacked
                     (Bomberman__Player *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bomberman__player__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bomberman__game_state__init
                     (Bomberman__GameState         *message)
{
  static const Bomberman__GameState init_value = BOMBERMAN__GAME_STATE__INIT;
  *message = init_value;
}
size_t bomberman__game_state__get_packed_size
                     (const Bomberman__GameState *message)
{
  assert(message->base.descriptor == &bomberman__game_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bomberman__game_state__pack
                     (const Bomberman__GameState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bomberman__game_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bomberman__game_state__pack_to_buffer
                     (const Bomberman__GameState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bomberman__game_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Bomberman__GameState *
       bomberman__game_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Bomberman__GameState *)
     protobuf_c_message_unpack (&bomberman__game_state__descriptor,
                                allocator, len, data);
}
void   bomberman__game_state__free_unpacked
                     (Bomberman__GameState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bomberman__game_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bomberman__player_move__init
                     (Bomberman__PlayerMove         *message)
{
  static const Bomberman__PlayerMove init_value = BOMBERMAN__PLAYER_MOVE__INIT;
  *message = init_value;
}
size_t bomberman__player_move__get_packed_size
                     (const Bomberman__PlayerMove *message)
{
  assert(message->base.descriptor == &bomberman__player_move__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bomberman__player_move__pack
                     (const Bomberman__PlayerMove *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bomberman__player_move__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bomberman__player_move__pack_to_buffer
                     (const Bomberman__PlayerMove *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bomberman__player_move__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Bomberman__PlayerMove *
       bomberman__player_move__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Bomberman__PlayerMove *)
     protobuf_c_message_unpack (&bomberman__player_move__descriptor,
                                allocator, len, data);
}
void   bomberman__player_move__free_unpacked
                     (Bomberman__PlayerMove *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bomberman__player_move__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bomberman__initial_state__init
                     (Bomberman__InitialState         *message)
{
  static const Bomberman__InitialState init_value = BOMBERMAN__INITIAL_STATE__INIT;
  *message = init_value;
}
size_t bomberman__initial_state__get_packed_size
                     (const Bomberman__InitialState *message)
{
  assert(message->base.descriptor == &bomberman__initial_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bomberman__initial_state__pack
                     (const Bomberman__InitialState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bomberman__initial_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bomberman__initial_state__pack_to_buffer
                     (const Bomberman__InitialState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bomberman__initial_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Bomberman__InitialState *
       bomberman__initial_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Bomberman__InitialState *)
     protobuf_c_message_unpack (&bomberman__initial_state__descriptor,
                                allocator, len, data);
}
void   bomberman__initial_state__free_unpacked
                     (Bomberman__InitialState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bomberman__initial_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor bomberman__tile__field_descriptors[3] =
{
  {
    "x",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Bomberman__Tile, x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "y",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Bomberman__Tile, y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Bomberman__Tile, type),
    &bomberman__tile_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bomberman__tile__field_indices_by_name[] = {
  2,   /* field[2] = type */
  0,   /* field[0] = x */
  1,   /* field[1] = y */
};
static const ProtobufCIntRange bomberman__tile__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor bomberman__tile__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bomberman.Tile",
  "Tile",
  "Bomberman__Tile",
  "bomberman",
  sizeof(Bomberman__Tile),
  3,
  bomberman__tile__field_descriptors,
  bomberman__tile__field_indices_by_name,
  1,  bomberman__tile__number_ranges,
  (ProtobufCMessageInit) bomberman__tile__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bomberman__map__field_descriptors[3] =
{
  {
    "width",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Bomberman__Map, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Bomberman__Map, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tiles",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Bomberman__Map, n_tiles),
    offsetof(Bomberman__Map, tiles),
    &bomberman__tile__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bomberman__map__field_indices_by_name[] = {
  1,   /* field[1] = height */
  2,   /* field[2] = tiles */
  0,   /* field[0] = width */
};
static const ProtobufCIntRange bomberman__map__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor bomberman__map__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bomberman.Map",
  "Map",
  "Bomberman__Map",
  "bomberman",
  sizeof(Bomberman__Map),
  3,
  bomberman__map__field_descriptors,
  bomberman__map__field_indices_by_name,
  1,  bomberman__map__number_ranges,
  (ProtobufCMessageInit) bomberman__map__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bomberman__player__field_descriptors[5] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Bomberman__Player, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_x",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Bomberman__Player, pos_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_y",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Bomberman__Player, pos_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alive",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Bomberman__Player, alive),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "points",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Bomberman__Player, points),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bomberman__player__field_indices_by_name[] = {
  3,   /* field[3] = alive */
  0,   /* field[0] = id */
  4,   /* field[4] = points */
  1,   /* field[1] = pos_x */
  2,   /* field[2] = pos_y */
};
static const ProtobufCIntRange bomberman__player__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor bomberman__player__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bomberman.Player",
  "Player",
  "Bomberman__Player",
  "bomberman",
  sizeof(Bomberman__Player),
  5,
  bomberman__player__field_descriptors,
  bomberman__player__field_indices_by_name,
  1,  bomberman__player__number_ranges,
  (ProtobufCMessageInit) bomberman__player__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bomberman__game_state__field_descriptors[3] =
{
  {
    "num_players",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Bomberman__GameState, num_players),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "players",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Bomberman__GameState, n_players),
    offsetof(Bomberman__GameState, players),
    &bomberman__player__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Bomberman__GameState, map),
    &bomberman__map__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bomberman__game_state__field_indices_by_name[] = {
  2,   /* field[2] = map */
  0,   /* field[0] = num_players */
  1,   /* field[1] = players */
};
static const ProtobufCIntRange bomberman__game_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor bomberman__game_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bomberman.GameState",
  "GameState",
  "Bomberman__GameState",
  "bomberman",
  sizeof(Bomberman__GameState),
  3,
  bomberman__game_state__field_descriptors,
  bomberman__game_state__field_indices_by_name,
  1,  bomberman__game_state__number_ranges,
  (ProtobufCMessageInit) bomberman__game_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bomberman__player_move__field_descriptors[4] =
{
  {
    "player_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Bomberman__PlayerMove, player_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "move_type",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Bomberman__PlayerMove, move_type),
    &bomberman__move_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_x",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Bomberman__PlayerMove, pos_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_y",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Bomberman__PlayerMove, pos_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bomberman__player_move__field_indices_by_name[] = {
  1,   /* field[1] = move_type */
  0,   /* field[0] = player_id */
  2,   /* field[2] = pos_x */
  3,   /* field[3] = pos_y */
};
static const ProtobufCIntRange bomberman__player_move__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor bomberman__player_move__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bomberman.PlayerMove",
  "PlayerMove",
  "Bomberman__PlayerMove",
  "bomberman",
  sizeof(Bomberman__PlayerMove),
  4,
  bomberman__player_move__field_descriptors,
  bomberman__player_move__field_indices_by_name,
  1,  bomberman__player_move__number_ranges,
  (ProtobufCMessageInit) bomberman__player_move__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bomberman__initial_state__field_descriptors[2] =
{
  {
    "player_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Bomberman__InitialState, player_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "map",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Bomberman__InitialState, map),
    &bomberman__map__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bomberman__initial_state__field_indices_by_name[] = {
  1,   /* field[1] = map */
  0,   /* field[0] = player_id */
};
static const ProtobufCIntRange bomberman__initial_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor bomberman__initial_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bomberman.InitialState",
  "InitialState",
  "Bomberman__InitialState",
  "bomberman",
  sizeof(Bomberman__InitialState),
  2,
  bomberman__initial_state__field_descriptors,
  bomberman__initial_state__field_indices_by_name,
  1,  bomberman__initial_state__number_ranges,
  (ProtobufCMessageInit) bomberman__initial_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue bomberman__tile_type__enum_values_by_number[5] =
{
  { "EMPTY", "BOMBERMAN__TILE_TYPE__EMPTY", 0 },
  { "BREAKABLE_WALL", "BOMBERMAN__TILE_TYPE__BREAKABLE_WALL", 1 },
  { "UNBREAKABLE_WALL", "BOMBERMAN__TILE_TYPE__UNBREAKABLE_WALL", 2 },
  { "BOMB", "BOMBERMAN__TILE_TYPE__BOMB", 3 },
  { "EXPLOSION", "BOMBERMAN__TILE_TYPE__EXPLOSION", 4 },
};
static const ProtobufCIntRange bomberman__tile_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex bomberman__tile_type__enum_values_by_name[5] =
{
  { "BOMB", 3 },
  { "BREAKABLE_WALL", 1 },
  { "EMPTY", 0 },
  { "EXPLOSION", 4 },
  { "UNBREAKABLE_WALL", 2 },
};
const ProtobufCEnumDescriptor bomberman__tile_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "bomberman.TileType",
  "TileType",
  "Bomberman__TileType",
  "bomberman",
  5,
  bomberman__tile_type__enum_values_by_number,
  5,
  bomberman__tile_type__enum_values_by_name,
  1,
  bomberman__tile_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue bomberman__move_type__enum_values_by_number[4] =
{
  { "IDLE", "BOMBERMAN__MOVE_TYPE__IDLE", 0 },
  { "PLACED_BOMB", "BOMBERMAN__MOVE_TYPE__PLACED_BOMB", 1 },
  { "MOVED", "BOMBERMAN__MOVE_TYPE__MOVED", 2 },
  { "RESTART", "BOMBERMAN__MOVE_TYPE__RESTART", 3 },
};
static const ProtobufCIntRange bomberman__move_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex bomberman__move_type__enum_values_by_name[4] =
{
  { "IDLE", 0 },
  { "MOVED", 2 },
  { "PLACED_BOMB", 1 },
  { "RESTART", 3 },
};
const ProtobufCEnumDescriptor bomberman__move_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "bomberman.MoveType",
  "MoveType",
  "Bomberman__MoveType",
  "bomberman",
  4,
  bomberman__move_type__enum_values_by_number,
  4,
  bomberman__move_type__enum_values_by_name,
  1,
  bomberman__move_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
