/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: game.proto */

#ifndef PROTOBUF_C_game_2eproto__INCLUDED
#define PROTOBUF_C_game_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Bomberman__Tile Bomberman__Tile;
typedef struct Bomberman__Map Bomberman__Map;
typedef struct Bomberman__Player Bomberman__Player;
typedef struct Bomberman__GameState Bomberman__GameState;
typedef struct Bomberman__PlayerMove Bomberman__PlayerMove;
typedef struct Bomberman__InitialState Bomberman__InitialState;


/* --- enums --- */

typedef enum _Bomberman__TileType {
  BOMBERMAN__TILE_TYPE__EMPTY = 0,
  BOMBERMAN__TILE_TYPE__BREAKABLE_WALL = 1,
  BOMBERMAN__TILE_TYPE__UNBREAKABLE_WALL = 2,
  BOMBERMAN__TILE_TYPE__BOMB = 3,
  BOMBERMAN__TILE_TYPE__EXPLOSION = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BOMBERMAN__TILE_TYPE)
} Bomberman__TileType;
typedef enum _Bomberman__MoveType {
  BOMBERMAN__MOVE_TYPE__IDLE = 0,
  BOMBERMAN__MOVE_TYPE__PLACED_BOMB = 1,
  BOMBERMAN__MOVE_TYPE__MOVED = 2,
  BOMBERMAN__MOVE_TYPE__RESTART = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BOMBERMAN__MOVE_TYPE)
} Bomberman__MoveType;

/* --- messages --- */

struct  Bomberman__Tile
{
  ProtobufCMessage base;
  int32_t x;
  int32_t y;
  Bomberman__TileType type;
};
#define BOMBERMAN__TILE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bomberman__tile__descriptor) \
, 0, 0, BOMBERMAN__TILE_TYPE__EMPTY }


struct  Bomberman__Map
{
  ProtobufCMessage base;
  int32_t width;
  int32_t height;
  size_t n_tiles;
  Bomberman__Tile **tiles;
};
#define BOMBERMAN__MAP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bomberman__map__descriptor) \
, 0, 0, 0,NULL }


struct  Bomberman__Player
{
  ProtobufCMessage base;
  int32_t id;
  int32_t pos_x;
  int32_t pos_y;
  protobuf_c_boolean alive;
  int32_t points;
};
#define BOMBERMAN__PLAYER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bomberman__player__descriptor) \
, 0, 0, 0, 0, 0 }


struct  Bomberman__GameState
{
  ProtobufCMessage base;
  int32_t num_players;
  size_t n_players;
  Bomberman__Player **players;
  Bomberman__Map *map;
};
#define BOMBERMAN__GAME_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bomberman__game_state__descriptor) \
, 0, 0,NULL, NULL }


struct  Bomberman__PlayerMove
{
  ProtobufCMessage base;
  int32_t player_id;
  Bomberman__MoveType move_type;
  int32_t pos_x;
  int32_t pos_y;
};
#define BOMBERMAN__PLAYER_MOVE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bomberman__player_move__descriptor) \
, 0, BOMBERMAN__MOVE_TYPE__IDLE, 0, 0 }


struct  Bomberman__InitialState
{
  ProtobufCMessage base;
  int32_t player_id;
  Bomberman__Map *map;
};
#define BOMBERMAN__INITIAL_STATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&bomberman__initial_state__descriptor) \
, 0, NULL }


/* Bomberman__Tile methods */
void   bomberman__tile__init
                     (Bomberman__Tile         *message);
size_t bomberman__tile__get_packed_size
                     (const Bomberman__Tile   *message);
size_t bomberman__tile__pack
                     (const Bomberman__Tile   *message,
                      uint8_t             *out);
size_t bomberman__tile__pack_to_buffer
                     (const Bomberman__Tile   *message,
                      ProtobufCBuffer     *buffer);
Bomberman__Tile *
       bomberman__tile__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   bomberman__tile__free_unpacked
                     (Bomberman__Tile *message,
                      ProtobufCAllocator *allocator);
/* Bomberman__Map methods */
void   bomberman__map__init
                     (Bomberman__Map         *message);
size_t bomberman__map__get_packed_size
                     (const Bomberman__Map   *message);
size_t bomberman__map__pack
                     (const Bomberman__Map   *message,
                      uint8_t             *out);
size_t bomberman__map__pack_to_buffer
                     (const Bomberman__Map   *message,
                      ProtobufCBuffer     *buffer);
Bomberman__Map *
       bomberman__map__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   bomberman__map__free_unpacked
                     (Bomberman__Map *message,
                      ProtobufCAllocator *allocator);
/* Bomberman__Player methods */
void   bomberman__player__init
                     (Bomberman__Player         *message);
size_t bomberman__player__get_packed_size
                     (const Bomberman__Player   *message);
size_t bomberman__player__pack
                     (const Bomberman__Player   *message,
                      uint8_t             *out);
size_t bomberman__player__pack_to_buffer
                     (const Bomberman__Player   *message,
                      ProtobufCBuffer     *buffer);
Bomberman__Player *
       bomberman__player__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   bomberman__player__free_unpacked
                     (Bomberman__Player *message,
                      ProtobufCAllocator *allocator);
/* Bomberman__GameState methods */
void   bomberman__game_state__init
                     (Bomberman__GameState         *message);
size_t bomberman__game_state__get_packed_size
                     (const Bomberman__GameState   *message);
size_t bomberman__game_state__pack
                     (const Bomberman__GameState   *message,
                      uint8_t             *out);
size_t bomberman__game_state__pack_to_buffer
                     (const Bomberman__GameState   *message,
                      ProtobufCBuffer     *buffer);
Bomberman__GameState *
       bomberman__game_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   bomberman__game_state__free_unpacked
                     (Bomberman__GameState *message,
                      ProtobufCAllocator *allocator);
/* Bomberman__PlayerMove methods */
void   bomberman__player_move__init
                     (Bomberman__PlayerMove         *message);
size_t bomberman__player_move__get_packed_size
                     (const Bomberman__PlayerMove   *message);
size_t bomberman__player_move__pack
                     (const Bomberman__PlayerMove   *message,
                      uint8_t             *out);
size_t bomberman__player_move__pack_to_buffer
                     (const Bomberman__PlayerMove   *message,
                      ProtobufCBuffer     *buffer);
Bomberman__PlayerMove *
       bomberman__player_move__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   bomberman__player_move__free_unpacked
                     (Bomberman__PlayerMove *message,
                      ProtobufCAllocator *allocator);
/* Bomberman__InitialState methods */
void   bomberman__initial_state__init
                     (Bomberman__InitialState         *message);
size_t bomberman__initial_state__get_packed_size
                     (const Bomberman__InitialState   *message);
size_t bomberman__initial_state__pack
                     (const Bomberman__InitialState   *message,
                      uint8_t             *out);
size_t bomberman__initial_state__pack_to_buffer
                     (const Bomberman__InitialState   *message,
                      ProtobufCBuffer     *buffer);
Bomberman__InitialState *
       bomberman__initial_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   bomberman__initial_state__free_unpacked
                     (Bomberman__InitialState *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Bomberman__Tile_Closure)
                 (const Bomberman__Tile *message,
                  void *closure_data);
typedef void (*Bomberman__Map_Closure)
                 (const Bomberman__Map *message,
                  void *closure_data);
typedef void (*Bomberman__Player_Closure)
                 (const Bomberman__Player *message,
                  void *closure_data);
typedef void (*Bomberman__GameState_Closure)
                 (const Bomberman__GameState *message,
                  void *closure_data);
typedef void (*Bomberman__PlayerMove_Closure)
                 (const Bomberman__PlayerMove *message,
                  void *closure_data);
typedef void (*Bomberman__InitialState_Closure)
                 (const Bomberman__InitialState *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    bomberman__tile_type__descriptor;
extern const ProtobufCEnumDescriptor    bomberman__move_type__descriptor;
extern const ProtobufCMessageDescriptor bomberman__tile__descriptor;
extern const ProtobufCMessageDescriptor bomberman__map__descriptor;
extern const ProtobufCMessageDescriptor bomberman__player__descriptor;
extern const ProtobufCMessageDescriptor bomberman__game_state__descriptor;
extern const ProtobufCMessageDescriptor bomberman__player_move__descriptor;
extern const ProtobufCMessageDescriptor bomberman__initial_state__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_game_2eproto__INCLUDED */
